### ISSUE TITLE
Syntax error: forgotten end-of-loop at around line 415

### ISSUE THREAD

**Issue by FrankUllmann** [Olf0/sfos-upgrade#23]
Within the current 2.7-1 release I found an error that prevented me from executing the script in the first run:
Within the for-loop starting from line 406 (current master branch) you forgot to end the (outer) if clause at around line 415 (between the emit_newline and the end-of-for-loop line).
Little hint: As I found out last week, bash also has an integrated syntax check with the option '-n', I used frequently since then, but maybe you know it already.
Nonetheless, great script and great work in general.

Best regards,
Frank

**Comment by Olf0** [comment]
Thanks a lot @FrankUllmann for detecting and reporting this (copy&paste of one line to little and insufficient quality assurance).
Fixed by commit [1c3ab07](https://github.com/Olf0/sfos-upgrade/commit/1c3ab07b9695e042177c63a24cb2ffd7e72da1c9).
