### ISSUE TITLE
OBS Build fails because of Release numbering

### ISSUE THREAD

**Issue by r0kk3rz** [Olf0/sfos-upgrade#41]
Unfortunately OBS doesn't use the `Release:` tag part of the RPM Spec and overwrites the `Version:` part with the latest tag information and expects that to be part of the tarball naming.

To fix this, i would suggest a change to the way you number releases, which can be a 3 digit versioning number.

eg. `3.5.8` instead of `3.5-8`

https://github.com/r0kk3rz/sfos-upgrade/commit/cbfd0046c8bed0271de22fe4aa55e91afc6ff20f
https://build.sailfishos.org/package/show/home:r0kk3rz/sfos-upgrade

**Comment by Olf0** [comment]
Thanks for explaining the ONS hurdles.

I might alter the version numbering scheme per next release to satisfy OBS, but would like to fully comprehend the issue first.
> Unfortunately OBS doesn't use the Release: tag part of the RPM Spec and overwrites the Version: part with the latest tag information and expects that to be part of the tarball naming.

That is for release 3.5-8:
* `Release:` tag part *8* is not used by OBS.
* "[OBS] overwrites the Version: part with the latest tag information ...", hence *3.5* would be overwritten with the git tag *3.5-8*, correct?
* "and expects that to be part of the tarball naming.", which is the case: ` sfos-upgrade-3.5-8.src.rpm`

So while I believe that I am causing some issue with OBS, from your description I do not comprehend yet what exactly OBS stumbles over.

**Comment by Olf0** [comment]
Note that for following the download link in the release section (e.g. `https://github.com/Olf0/sfos-upgrade/archive/3.5-8.tar.gz`) one has to follow http-redirections in order to download e.g. `sfos-upgrade-3.5-8.tar.gz`.
The correct construction of canonical download links was discussed at [issue \#36](https://github.com/Olf0/sfos-upgrade/issues/36#issuecomment-536327189) and has been introduced as `Source:` tag in the spec file ever since MR #37.  I wonder, why OBS does not simply use this link, as this is what build systems should do AFAIU.

**Comment by Olf0** [comment]
Oh, I even do not know if OBS starts from the raw TARball (as assumed in above comment) or from the SRPM (which I started releasing to satisfy the needs of build systems. ;-\ )?!?

**Comment by Olf0** [comment]
Ah, now I remember my comments at your [commit \#8949a8](https://github.com/r0kk3rz/sfos-upgrade/commit/8949a808921367550b5ee13797da1090ffd46f7b#commitcomment-35089971) and now see its updated version [\#cbfd004](https://github.com/r0kk3rz/sfos-upgrade/commit/cbfd0046c8bed0271de22fe4aa55e91afc6ff20f).

**Comment by r0kk3rz** [comment]
The way OBS works is that it fetches the Git repo and tarballs it, and mangles the naming of it to match the tag, rather than downloading anything pre organised. It ignores everything except the final name of the tarball in the `Source:` part, which unfortunately needs to match what it creates.

It also seems to ignore hyphens in the tag, so `3.5-8` turns into just `3.5`, which then doesn't match the name in the `Source:`... and then the build fails.

So I would suggest switching from `3.5-8` to `3.5.8`, which is a pain, but I don't see an alternative really.

It would be nice to get this building on OBS because then we can easily add it to ported devices, which do not have an easy method of updating other than the usual ssu/zypper dance

**Comment by Olf0** [comment]
Thank you for your explanations.  There are a couple of aspects to this:
* Although I cannot really believe that OBS is so extremely inflexible, I do understand that (at least) its default configuration is.  As I will not start studying the OBS documentation to determine if and how this may be achieved, I concur that adapting my versioning scheme is the easier route.
* I intended to switch to a classic, three field, semantic versioning scheme for long, but never had sufficient impetus to introduce it.  So let accommodating OBS be the trigger now.

Thus I introduced these changes according to what I gathered from your description of OBS' needs:
* [sfos-upgrade 3.6.1](https://github.com/Olf0/sfos-upgrade/releases/tag/3.6.1)
* [mount-sdcard 1.2.0](https://github.com/Olf0/mount-sdcard/releases/tag/1.2.0)
* [crypto-sdcard 1.2.0](https://github.com/Olf0/crypto-sdcard/releases/tag/1.2.0)
* [crypto-sdcard_sbj 1.2.0](https://github.com/Olf0/crypto-sdcard_sbj/releases/tag/1.2.0)
* [obexd-contentfilter-off 1.1.0](https://github.com/Olf0/obexd-contentfilter-off/releases/tag/1.1.0)

Can you please check, if one of these is working fine with OBS now.
If positive, please be so kind to upload them all at the [SailfishOS-OBS](https://build.sailfishos.org/).
If not, please report back and I will try to implement what is missing.

**Comment by r0kk3rz** [comment]
It's not really 'OBS' thats being inflexible, but the tar_git plugin in use by build.sailfishos.org.

Thanks for adopting the new versioning though, this now seems happy on OBS:
https://build.sailfishos.org/package/show/home:r0kk3rz/sfos-upgrade

**Comment by Olf0** [comment]
BTW, you should solely use the [git tags](https://github.com/Olf0/sfos-upgrade/tags) of the [release versions](https://github.com/Olf0/sfos-upgrade/releases), otherwise you might easily retrieve a non-functional version (which I am trying to avoid for releases 😋).

Today this would have been the tag **3.6.1** instead of the virtual, autogenerated tag of the (master) branch head **3.6.1+master.20191228030140.8.gccf3943** .
Consequently what you downloaded and built per OBS is a mix of v3.6.1 with changes destined for v3.6.2!

**Comment by r0kk3rz** [comment]
Good point, i was mostly just checking the packaging has been fixed. I've now added the appropriate commit to match the proper version

**Comment by Olf0** [comment]
> It's not really 'OBS' thats being inflexible, but the tar_git plugin in use by build.sailfishos.org.

Thanks again for pointing this out.  Unfortunately I did not remember this hint two years later, ran into the same issues again, was hinted again and finally analysed [Jolla's `tar_git`](https://github.com/MeeGoIntegration/obs-service-tar-git) and submitted this analysis by [obs-service-tar-git PR \#4](https://github.com/MeeGoIntegration/obs-service-tar-git/pull/4).
