### ISSUE TITLE
Properly support community adaptions

### ISSUE THREAD

**Issue by Olf0** [Olf0/sfos-upgrade#43]
To properly support community adaptions of SailfishOS is probably a longer endeavor, as there currently are many unknowns (for me, at least):

* As I do not own or have access to a device with a community adaption, I never had a chance to try `sfos-upgrade` on one.  Hence the current, "official"  state of support for community adaptions is something between "unknown" and "unsupported".
* OTOH, @r0kk3rz' side note ([the last paragraph of this comment](https://github.com/Olf0/sfos-upgrade/issues/41#issuecomment-566347446)) sounds as if `sfos-upgrade` does already basically work on devices with community adaptions of SailfishOS.

As `sfos-upgrade` up to now always uses `version --dup` to perform the upgrade proper, which checks if `rnd-dist-upgrade` is installed (usually in `/usr/bin/`) and uses either that or `pkcon upgrade`, respectively complains (since  SFOS3.2.1?), I now wonder why the "zypper dance" / `zypper upgrade` is the primary suggestion from SailfishOS porters for upgrading installations of community adaptions.

Hence I compiled a list of simple questions, trying to pose them in a way that they can be answered with "Yes" or "No".

For my basic understanding:

1. Does the GUI page *Settings -> Sailfish OS updates* exist on "community devices"?
2. If so, does it work?
3. Is the Jolla Store app available?
4. If so, does it work?
   (Granted that one created an Jolla Store account, is logged in to it and only for apps free of charge.)

To understand the technical differences:

5. Is the `version` shell script preinstalled (usually in `/usr/bin/`)?
6. Is the `rnd-dist-upgrade` binary installed (usually in `/usr/bin/`), when "developer mode" is enabled in the SailfishOS' Settings (which I assume every user of a "community device" has)?
7. Do you understand, why `zypper upgrade` is preferred over `pkcon upgrade` by "community porters", in contrast to Jolla's general preference of `pkcon` over `zypper` (also specifically for the upgrade case)?
  Both, `pkcon` and `zypper` use `libzypp` as backend (on SailfishOS) and hence should yield the same package transactions and result.  Maybe `zypper`'s more elaborate output and configurability is the only reason, why porters prefer it.

**Comment by r0kk3rz** [comment]
>     1. Does the GUI page _Settings -> Sailfish OS updates_ exist on "community devices"?
Yes, which leads to some confusion for users

>     2. If so, does it work?
No, it doesn't

>     3. Is the Jolla Store app available?
Yes, Jolla store app can be activated on request
>     4. If so, does it work?
Yes, if activated properly on the store backend


>     1. Is the `version` shell script preinstalled (usually in `/usr/bin/`)?
Yes

>     2. Is the `rnd-dist-upgrade` binary installed (usually in `/usr/bin/`), when "developer mode" is enabled in the SailfishOS' Settings (which I assume every user of a "community device" has)?
Yes

>     3. Do you understand, why `zypper upgrade` is preferred over `pkcon upgrade` by "community porters", in contrast to Jolla's general preference of `pkcon` over `zypper` (also specifically for the upgrade case)?
>        Both, `pkcon` and `zypper` use `libzypp` as backend (on SailfishOS) and hence should yield the same package transactions and result.  Maybe `zypper`'s more elaborate output and configurability is the only reason, why porters prefer it.

Just convention mostly, i don't think there's a technical reason for it and as you say both paths should be equivalent

**Comment by Olf0** [comment]
Thank you for your answers.

Sorry, I actually missed to ask the final question:

8. Did **sfos-upgrade** (and hence ultimately **rnd-dist-upgrade**, when it is installed) successfully upgrade a SailfishOS installation on a device with a community adaption?

If the answer is "yes", I will try to understand why the porters advise to perform the "zypper dance", as it seems to be unnecessary then.

**Comment by Olf0** [comment]
@r0kk3rz, btw:

> > 1. Does the GUI page _Settings -> Sailfish OS updates_ exist on "community devices"?

> Yes, which leads to some confusion for users

This should be relatively easy to resolve with a Patch for [Patchmanager](https://github.com/sailfishos-patches/patchmanager) (preferably for its [web catalog](https://github.com/sailfishos-patches/patchmanager#web-catalog-for-patches)), which disables ("grays out") or (simpler) eliminates (si

**Comment by r0kk3rz** [comment]
I haven't personally used sfos-upgrade to update a ported device (due to the before mentioned stop release issue), but one of my users has and reported everything was ok.

In general there isn't any significant difference in updating official or ported devices

**Comment by Olf0** [comment]
Well, I would rather have a recent, first hand report, because lately (with SailfishOS 3.2.1?) Jolla eliminated the pendant of the "zypper dance" (around **pkcon upgrade**) from the **version** script (when called with **--dup**), hence it now solely relies on Jolla's binary **rnd-dist-upgrade**.
