### ISSUE TITLE
Intended license change from MIT to LGPL-2.1-only

### ISSUE THREAD

**Issue by Olf0** [Olf0/sfos-upgrade#49]
@pcfe, @direc85, @Okxa, @Self-Perfection,

I want to change the license from MIT to LGPL-2.1-only.
Because you all contributed to *sfos-upgrade*, I want to align this license change with you.
If you do not concur with this change, please notify me (preferably here in this issue) before 1 May 2021.

**Comment by pcfe** [comment]
_MIT → LGPLv2.1-only_ is fine by me.

**Comment by direc85** [comment]
I don't mind the license change!

**Comment by Olf0** [comment]
@pcfe, @direc85, @Okxa, @Self-Perfection,
thank you for supporting this change, either by explicit confirming your support or passively accepting it by letting the deadline pass.
