### ISSUE TITLE
Support for themepacksupport

### ISSUE THREAD

**Issue by fravaccaro** [Olf0/sfos-upgrade#6]
Hi,

Would you mind adding the pre-upgrade script for themepacksupport?

Its path is /usr/share/harbour-themepacksupport/ocr.sh

(It restores default themes/display options in one click. I have a systemd service if the upgrade is triggered via UI, but I'm pretty sure it doesn't work if the upgrade is triggered via cli.).

Br,

Fra

**Comment by Olf0** [comment]
I don't quite understand: What has to be done before an upgrade WRT to your "theme pack support"?
Just calling `/usr/share/harbour-themepacksupport/ocr.sh` without parameters?
How do I detect for sure, if "theme pack support" is installed (e.g., before calling `ocr.sh`)?

**Comment by Olf0** [comment]
To ask more specifically:
1. AFAIU the Theme pack support does not use Patchmanager at all.  Is that correct?
2. Installing your Theme pack support does alter extant files deployed by SailfishOS proper.  Is that correct?
3. Executing`/usr/share/harbour-themepacksupport/ocr.sh` reverts exactly those changes.  Is that correct?
4. Thus you would like to see something added like this:
```
if [ -x /usr/share/harbour-themepacksupport/ocr.sh ]
then
  echo "- Disabling Theme pack support."
  /usr/share/harbour-themepacksupport/ocr.sh
fi
```
 Is that correct?

**Comment by fravaccaro** [comment]
Exactly, the script uses no parameters, so something like 

```
if [ -d /usr/share/harbour-themepacksupport/ocr.sh ]
then
  echo "- Disabling Theme pack support."
  /usr/share/harbour-themepacksupport/ocr.sh
fi 
```

would be enough. 

The ocr script restores icons, fonts and display density settings, so it's basically like it has never been used. Theme pack support doesn't uses patchmanager at all.

Thank you for your interest in supporting it :)

**Comment by Olf0** [comment]
Added by commit f369484.
