### ISSUE TITLE
[Bug] final_sfos_releases: unbound variable

### ISSUE THREAD

**Issue by AmbossII** [Olf0/sfos-upgrade#64]
**SailfishOS VERSION** (Settings → About product → Build): 4.3.0.15
<br />**HARDWARE** (Settings → About product → Manufacturer & Product name): Sony Xperia XA2 (4113)
<br />**sfos-upgrade VERSION** ( `rpm -qi sfos-upgrade` ): 3.9.4-release3
<br />

#### BUG DESCRIPTION
/usr/bin/sfos-upgrade: line 177: final_sfos_releases: unbound variable
/usr/bin/sfos-upgrade: line 196: final_sfos_releases: unbound variable
seems the newly added feature pulling releases from sailfishos does not work.

#### STEPS TO REPRODUCE
start from 4.3.0.**12**
run sfos-update 4.4.0.64 (can't remember, which version it was run on)
stop release 4.3.0.**15** get's detected
install, reboot, run post_sfos-upgrade
this refreshes repositories
at some point the new version 3.9.4.-release3 of sfos-upgrade get's installed
the remaining step _sfos-update 4.4.0.64_ is not successful because of error message for line 177 and 196

#### ADDITIONAL INFORMATION
at the time of reporting, /sailfishos/docs.sailfishos.org/master/Releases/README.md does not contain 4.4.0.64 yet, while coderus.openrepos.net/whitesoft/sailversion does

**Comment by Olf0** [comment]
Thank you very much for this bug report.  It is just a idiotic think'o due to implementing this too hastily.

I will try to make a new release before 2022-05-27.

**Comment by Olf0** [comment]
This should be fixed in v3.9.5: Please check.

**Comment by AmbossII** [comment]
I have already updated the phone in question but I was able to verify correctness anyway, as I have two XA2s.
The one still with 3.9.4 is failing for _sfos-upgrade --verify_ at line 177
The other updated to 3.9.5 is passing the whole _sfos-upgrade --verify_ as it is supposed to.
Can't check the actual update procedure but I think that should work too.

**Comment by Olf0** [comment]
Thank you very much.

**Comment by beckmi** [comment]
The new version worked fine for me (upgrade from 4.4.0.58 to 4.4.064 on XA2) but to upgrade sfos-upgrade via Storeman I needed to deinstall and reinstall sfos-upgrade. It seems that Storeman does not recognise the new version as upgrade.

**Comment by Olf0** [comment]
Please see https://openrepos.net/comment/40691#comment-40691
